name: upload_Artifact
on: workflow_dispatch
jobs:
  upload:
    name: upload
    runs-on: ubuntu-latest
    steps:
      # creation du fichier
      - name: create_file
        run: echo "coucou" > artifact.txt
        # upload du fichier
      - name: upload_artifact
        # on utilise l'action github qui permet de faire l'upload
        uses: actions/upload-artifact@v3
        # on lui passe en parametre le nom et le chemin du fichier a uploader
        with:
          name: artifact
          path: artifact.txt
  download:
    needs: upload
    name: download
    runs-on: ubuntu-latest
    steps:
      - name: download_file
      # on récupère le fichier via l'action download-artifact
        uses: actions/download-artifact@v3
        with:
        # on lui précise le nom de l'artifact à récupérer, sinon
        # par defaut ce sera "artifact"
          name: artifact
      - name: read-file
      # commande linux pour lire la contenu d'un fichier
        run: cat artifact.txt