name: Amnesia
# event qui trigger le workflow manuellement
on: workflow_dispatch

env:
  NAME: Francois

jobs:
  say_hello:
    runs-on: ubuntu-latest
    env:
      ENTREPRISE: Semifir
    steps:
      - name: Dit Bonjour
        run: echo "Salut $NAME ! tu travail chez $ENTREPRISE ?"
        alors bon $DAY à toi
        env:
          DAY: Lundi
      -name: Lundi ?
        run: echo "Quel jour somme nous ? $DAY ?"
  say_goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: "Dit au revoir"
        run: echo "au revoir $NAME ! tu travail
        pour quelle entreprise ? $ENTREPRISE ?"