name: nf4-do-01
on:
  issues:
    types:
      - assigned

jobs:
  nf4-do-01:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: create_branche
        run: |
          issue_number=$(echo "${{ github.event.issue.number }}")
          branch_name="issue-$issue_number"
          git checkout -b "$branch_name"
      - name: Push branch
        run: |
          git push origin "$branch_name"


