name: nf4-do-01
on: workflow_dispatch

jobs:
  create_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: create_branche
        run: |
          git branch testing