name: nf8_do_01
on:
  pull_request:
    branches: [feature]
    types: [opened, synchronize]

jobs:
  nf8_do_01:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x]
    if: startsWith(github.head_ref, 'feature/')
    steps:
      - uses: actions/checkout@v3
      - name: node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo npm run test
