name: pull_or_push

on: [push,pull]

env:
  REQUETE: github.event_name

jobs:
  push:
    runs-on: ubuntu-latest
    if: ${{github.event_nameE == 'push'}}
      - uses: actions/checkout@v3
      - name: "push"
        run: echo "C'est un push"

  pull_requete:
    runs-on: ubuntu-latest
    if: ${{github.event_name == 'pull_request'}}
      - uses: actions/checkout@v3
      - name: "pull_request"
        run: echo "C'est un pull_request"