name: pull_or_push

on: [push,pull_request]

env:
  PUSH: push
  PULL_REQUETE: pull

jobs:
  on_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "push"
        run: echo "C'est un push"

  on_pull_requete:
    runs-on: ubuntu-latest
    steps:
      if: ${{github.event_name == 'pull_request'}}
        - uses: actions/checkout@v3
        - name: "pull_request"
          run: echo "C'est un pull_request"