name: exo_trigger_02
on: workflow_dispatch
  #pull_request:
    #types: [closed]
jobs:
  trigger_02:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Pull request merged
        run: echo "merged"