name: exo_trigger_03

on: workflow_dispatch
  #workflow_run:
   # workflows: [exo_trigger_02]
   # types: [completed]

jobs:
  next_one:
    runs-on: ubuntu-latest
    steps:
      - name: "next one"
        run: echo "next one"
